//! The TypeScript declarations for the `baudelaire:*` modules, as one ambient
//! `.d.ts` built from the registry that serves them.

use std::path::PathBuf;

use crate::codegen::Value;
use crate::config::Config;
use crate::generated::{File, Generated};
use crate::render::AssetMap;
use crate::world::BuildContext;

use super::{ModuleCx, builtin};

/// Every module's declaration, as one file.
pub struct Declarations {
    source: String,
    /// The specifiers declared, in the order they appear.
    modules: Vec<String>,
}

impl Declarations {
    /// Where the file goes, relative to the project root: project scratch,
    /// which is outside every root `serve` watches, so writing it cannot
    /// retrigger the build that wrote it.
    pub fn path() -> PathBuf {
        Config::scratch(crate::config::Scratch::Generated).join("baudelaire.d.ts")
    }

    const HEADER: &'static str = "// Generated by baudelaire. Rewritten on every build; edits are lost.\n\
         // Put this file on your `tsconfig.json` `include` list to type the\n\
         // `baudelaire:*` modules a bundled entry imports.\n";

    /// The declarations for `config`'s project. The data-shaped modules are
    /// typed from the config rather than the page set, so a project that has
    /// never been built still gets its own keys.
    pub fn of(config: &Config) -> Self {
        let context = Value::from(&BuildContext::of(config));
        Self::from(&ModuleCx {
            config,
            pages: &[],
            assets: &AssetMap::new(config.asset_prefix()),
            context: &context,
            sections: &Value::dict::<&str>([]),
        })
    }

    pub fn modules(&self) -> &[String] {
        &self.modules
    }
}

/// Built from the same registry that serves the modules, so a module cannot be
/// served without being declared.
impl From<&ModuleCx<'_>> for Declarations {
    fn from(cx: &ModuleCx) -> Self {
        let mut declared: Vec<_> = builtin()
            .iter()
            .flat_map(|module| module.types(cx))
            .collect();
        declared.sort_by(|(a, _), (b, _)| a.cmp(b));
        let source = std::iter::once(Self::HEADER.to_owned())
            .chain(declared.iter().map(|(name, dts)| dts.module(name)))
            .collect::<Vec<_>>()
            .join("\n");
        let modules = declared.into_iter().map(|(name, _)| name).collect();
        Self { source, modules }
    }
}

impl Generated for Declarations {
    fn files(&self) -> Vec<File> {
        vec![File::new(Self::path(), self.source.clone())]
    }
}
