//! The TypeScript declarations for the `baudelaire:*` modules.
//!
//! The JavaScript counterpart of [`crate::world::module::package`]: the modules
//! are generated during a build, so nothing on disk holds them and an editor
//! reads every import of one as unknown. This turns the same registry that
//! serves them into one ambient `.d.ts`, which a build writes into project
//! scratch and [`crate::mirror`] writes on demand.

use std::path::PathBuf;

use crate::codegen::Value;
use crate::config::Config;
use crate::generated::{File, Generated};
use crate::render::AssetMap;
use crate::world::BuildContext;

use super::{ModuleCx, builtin};

/// Every module's declaration, as one file.
pub struct Declarations {
    source: String,
    /// The specifiers declared, in the order they appear, for a caller that
    /// reports what it wrote.
    modules: Vec<String>,
}

impl Declarations {
    /// Where the file goes, relative to the project root.
    ///
    /// Project scratch, with the generated typst tables: regenerable,
    /// gitignored, swept by `clean`, and outside every root `serve` watches, so
    /// writing it cannot retrigger the build that wrote it.
    pub fn path() -> PathBuf {
        Config::scratch("generated").join("baudelaire.d.ts")
    }

    /// The header the file opens with: it is generated state, and a reader who
    /// finds it has to know both where it came from and what to do with it.
    const HEADER: &'static str = "// Generated by baudelaire. Rewritten on every build; edits are lost.\n\
         // Put this file on your `tsconfig.json` `include` list to type the\n\
         // `baudelaire:*` modules a bundled entry imports.\n";

    /// The declarations for `config`'s project.
    ///
    /// Data-shaped modules (`site`, `config`, `i18n`) are typed from the site's
    /// own values, so a project that has never been built still gets its own
    /// keys: they come from the config, not from the page set. Nothing is typed
    /// from a page, and the asset map's *type* is the same however many entries
    /// it holds, so both are left empty here.
    pub fn of(config: &Config) -> Self {
        let context = Value::from(&BuildContext::of(config));
        Self::from(&ModuleCx {
            config,
            pages: &[],
            assets: &AssetMap::new(config.asset_prefix()),
            context: &context,
            sections: &Value::dict::<&str>([]),
        })
    }

    /// The specifiers this file declares, as a reader names them.
    pub fn modules(&self) -> &[String] {
        &self.modules
    }
}

/// Built from the same registry that serves the modules, so a module cannot be
/// served without being declared.
impl From<&ModuleCx<'_>> for Declarations {
    fn from(cx: &ModuleCx) -> Self {
        // Sorted by specifier, so the file is stable across runs whatever order
        // the registry holds.
        let mut declared: Vec<_> = builtin()
            .iter()
            .flat_map(|module| module.types(cx))
            .collect();
        declared.sort_by(|(a, _), (b, _)| a.cmp(b));
        let source = std::iter::once(Self::HEADER.to_owned())
            .chain(declared.iter().map(|(name, dts)| dts.module(name)))
            .collect::<Vec<_>>()
            .join("\n");
        let modules = declared.into_iter().map(|(name, _)| name).collect();
        Self { source, modules }
    }
}

impl Generated for Declarations {
    fn files(&self) -> Vec<File> {
        vec![File::new(Self::path(), self.source.clone())]
    }
}
