// Shared pieces of the documentation shell. `page.typ` and `list.typ` both
// import `shell` from here, so the header, sidebar and footer are written once.
//
// `h` is `html.elem` without the `attrs:` wrapper: named arguments become
// attributes, positional ones become children, `true` writes a bare attribute
// and `none` drops it. `classes` joins class names and skips what is absent.
#import "@baudelaire/html:0.1.0": classes, h
#import "@baudelaire/site:0.1.0": title as site-title

#let link-to(href, label) = h("a", href: href, label)

// `sections(page.lang)` is the build's own view of `content/`: a tree of
// `(id, pages: ((url, title), ..), children: (..))`, one node per directory,
// with each collection's pages already in its configured sort order. The
// sidebar reads it rather than a hand-kept list, so it cannot drift from the
// pages on disk or from the prev/next pager, which reads the same source.
#let titlecase(s) = if s == "" { s } else { upper(s.slice(0, count: 1)) + s.slice(1) }

#let nav-section(section) = h("div", class: "nav-group")[
  #h("p", class: "nav-title", titlecase(section.id))
  #if section.pages.len() > 0 {
    h("ul", for entry in section.pages { h("li", link-to(entry.url, entry.title)) })
  }
  // A subdirectory of `content/guide/` nests here, same shape, one level in.
  #for child in section.children { nav-section(child) }
]

#let sidebar(sections) = h(
  "nav",
  class: "sidebar",
  id: "sidebar",
  aria-label: "Documentation",
  for section in sections { nav-section(section) },
)

// The palette generated by `generate { search { client #true } }` opens on any
// element carrying `data-search-open`, so the button needs no script of its own.
#let search-trigger = h(
  "button",
  class: "search-trigger",
  type: "button",
  aria-label: "Search",
  aria-keyshortcuts: "Control+K /",
  data-search-open: true,
  {
    h("span", "Search")
    h("kbd", "/")
  },
)

#let site-header = h("header", class: "site-header")[
  #h("a", class: "skip-link", href: "#main", "Skip to content")
  #h("a", class: "brand", href: "/", site-title)
  #h("nav", class: "top-nav", aria-label: "Primary")[
    #link-to("/guide/", "Guide")
  ]
  #search-trigger
]

// A prev/next pager over `page.nav`, which baudelaire fills from the page's
// neighbours in its collection. Either side may be `none` at the ends; the
// empty `<span>` keeps "next" against the right edge.
#let pager(nav, label: "Page navigation") = {
  if nav.prev != none or nav.next != none {
    h("nav", class: "pager", aria-label: label, {
      if nav.prev != none { link-to(nav.prev.url, "← " + nav.prev.title) } else { h("span") }
      if nav.next != none { link-to(nav.next.url, nav.next.title + " →") }
    })
  }
}

#let callout(body, kind: "note") = h("div", class: classes("callout", "callout-" + kind))[
  #h("p", class: "callout-label", upper(kind))
  #body
]

// The whole document except its `<head>`: templates must never emit `<html>`,
// `<head>` or `<body>`, because typst-html owns those. `set document(title: ..)`
// is how the `<title>` gets set.
#let shell(title, body, sections: ()) = {
  set document(title: title)

  h("link", rel: "stylesheet", href: "/assets/style.css")
  site-header
  h("div", class: "layout")[
    #sidebar(sections)
    #h("main", class: "content", id: "main")[
      #h("article")[
        #h("h1", title)
        #body
      ]
    ]
  ]
  h("footer", class: "site-footer")[
    #h("span")[Built with #link-to("https://baudelaire.cstef.dev", "Baudelaire")]
  ]
  // Generated by `generate { search { client #true } }`, alongside the index it
  // fetches. It mounts itself, so nothing here has to call it.
  h("script", type: "module", src: "/search.js")
}
