//! Virtual Typst modules: the `@baudelaire/*` packages a template imports with
//! nothing on disk, each generated by a [`Module`] and served by [`Files`].
//!
//! Nothing volatile may be baked into a module's source: it is fingerprinted
//! whole, so a commit hash in one would rebuild the site on every commit.

use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicBool, Ordering};

use typst::diag::{FileError, FileResult, PackageError};
use typst::ecow::EcoString;
use typst::foundations::Bytes;
use typst::syntax::{
    FileId, VirtualPath, VirtualRoot,
    package::{PackageSpec, PackageVersion},
};
use typst_kit::files::{FileLoader, FsRoot, SystemFiles};
use typst_kit::packages::SystemPackages;

pub mod package;

mod builtin;

pub use builtin::{Html, Toc};
pub use package::{Package, Packages};

use super::generated::Table;
use crate::codegen::{Let, Value};
use crate::config::dispatch::Keys;
use crate::graph::Hash;

/// The package namespace every generated module lives in.
const NAMESPACE: &str = "baudelaire";

/// The version every generated module is served at, which versions the *module
/// API* and never the binary.
const VERSION: PackageVersion = PackageVersion {
    major: 0,
    minor: 1,
    patch: 0,
};

/// The manifest typst reads to find a package's entrypoint, and the entrypoint
/// every generated manifest names.
const MANIFEST: &str = "typst.toml";
const ENTRYPOINT: &str = "lib.typ";

/// The read-only build data every virtual module generates from.
pub(super) struct ModuleCx<'a> {
    /// The `sys.inputs.baudelaire` value, which `@baudelaire/site` and its
    /// JavaScript counterpart both serve.
    pub context: &'a Value,
    /// How this site reads markdown, so `@baudelaire/markdown` renders a
    /// fragment the way it would render a `.md` page.
    #[cfg(feature = "markdown")]
    pub markdown: &'a crate::config::MarkdownConfig,
    /// The files `paths { sources }` declared, and the list the mount is built
    /// from, so a name a page can import is one the store can answer.
    pub sources: &'a [(String, std::path::PathBuf)],
}

/// One provider of an `@baudelaire/*` Typst module: a set of generated
/// bindings over a hand-written body.
trait Module {
    /// The name this module is imported under: `@baudelaire/<name>`.
    fn name(&self) -> &'static str;

    /// The values bound at the top of the module, in emission order.
    fn bindings(&self, cx: &ModuleCx) -> Vec<(String, Value)>;

    /// The module's hand-written Typst, appended after the bindings, so a
    /// binding is always in scope for the code that closes over it.
    fn body(&self) -> &'static str;

    /// The Typst source of the module's entrypoint.
    fn source(&self, cx: &ModuleCx) -> String {
        let mut out = String::new();
        for (name, value) in self.bindings(cx) {
            let _ = writeln!(out, "{}", Let(&name, &value));
        }
        out.push_str(self.body());
        out
    }
}

/// The registered virtual modules.
fn builtin() -> Vec<Box<dyn Module>> {
    vec![
        Box::new(builtin::Html),
        Box::new(builtin::Site),
        Box::new(builtin::Sources),
        Box::new(builtin::Toc),
        #[cfg(feature = "markdown")]
        Box::new(builtin::Markdown),
    ]
}

/// The modules whose source the build writes to a file instead of generating
/// into memory, each being derived from the whole page set.
pub(crate) const FILES: [&str; 2] = [SECTIONS, PAGES];

/// The section tree module: `sections(lang)`.
pub(crate) const SECTIONS: &str = "sections";

/// The page catalogue module: `pages(lang)`.
pub(crate) const PAGES: &str = "pages";

/// Where a module's entrypoint source comes from.
enum Entrypoint {
    /// Generated with the world and served from memory, holding nothing
    /// volatile, so one fingerprint covers it for the whole site.
    Memory(Bytes),
    /// A file the build writes before any page compiles, served by path, so
    /// typst's own tracking scopes it to the templates that import it.
    File(PathBuf),
}

/// The modules of one build, as `name -> entrypoint`.
struct Modules {
    entrypoints: BTreeMap<&'static str, Entrypoint>,
    /// Whether this build has written the file-backed tables yet, and whether
    /// anything read one before it did.
    tables: Tables,
}

/// How far this build has got with the file-backed tables.
///
/// A page evaluated during discovery can read one before it is written, and the
/// store caches that empty answer, so the early read has to be recorded.
#[derive(Default)]
struct Tables {
    written: AtomicBool,
    read_early: AtomicBool,
}

impl Modules {
    fn new(cx: &ModuleCx, root: &Path) -> Self {
        let mut entrypoints: BTreeMap<&'static str, Entrypoint> = builtin()
            .iter()
            .map(|module| {
                (
                    module.name(),
                    Entrypoint::Memory(Bytes::from_string(module.source(cx))),
                )
            })
            .collect();
        for name in FILES {
            entrypoints.insert(name, Entrypoint::File(root.join(Table::of(name))));
        }
        Self {
            entrypoints,
            tables: Tables::default(),
        }
    }

    /// Record that this build's tables are on disk, and report whether anything
    /// read one before they were, which is the caller's cue to drop what the
    /// file store cached.
    fn published(&self) -> bool {
        self.tables.written.store(true, Ordering::Relaxed);
        self.tables.read_early.load(Ordering::Relaxed)
    }

    /// The file backing `id`, when it names a file-backed module's entrypoint.
    fn file(&self, id: FileId) -> Option<&Path> {
        let spec = Self::owner(&id)?;
        if id.vpath().get_without_slash() != ENTRYPOINT {
            return None;
        }
        match self.entrypoints.get(spec.name.as_str())? {
            Entrypoint::File(path) => Some(path),
            Entrypoint::Memory(_) => None,
        }
    }

    /// The generated module `id` names a file of, or `None` for a real file.
    fn owner(id: &FileId) -> Option<&PackageSpec> {
        match id.root() {
            VirtualRoot::Package(spec) if spec.namespace == NAMESPACE => Some(spec),
            _ => None,
        }
    }

    /// Serve a file from the generated module named by `spec`.
    fn load(&self, spec: &PackageSpec, vpath: &VirtualPath) -> FileResult<Bytes> {
        let Some((name, entrypoint)) = self.entrypoints.get_key_value(spec.name.as_str()) else {
            return Err(FileError::Package(PackageError::Other(Some(
                self.unknown(&spec.name),
            ))));
        };
        if spec.version != VERSION {
            return Err(FileError::Package(PackageError::Other(Some(
                Self::wrong_version(&spec.name),
            ))));
        }
        match vpath.get_without_slash() {
            MANIFEST => Ok(Bytes::from_string(Self::manifest(&spec.name))),
            ENTRYPOINT => match entrypoint {
                Entrypoint::Memory(source) => Ok(source.clone()),
                Entrypoint::File(path) => {
                    if !self.tables.written.load(Ordering::Relaxed) {
                        self.tables.read_early.store(true, Ordering::Relaxed);
                    }
                    match std::fs::read(path) {
                        Ok(bytes) => Ok(Bytes::new(bytes)),
                        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                            Ok(Bytes::from_string(Table::empty(name).source()))
                        }
                        Err(e) => Err(FileError::from_io(e, path)),
                    }
                }
            },
            _ => Err(FileError::NotFound(PathBuf::from(vpath.get_with_slash()))),
        }
    }

    /// The message for an import of a module that does not exist, suggesting a
    /// nearest match off the registry itself.
    fn unknown(&self, name: &str) -> EcoString {
        let names: Vec<&str> = self.entrypoints.keys().copied().collect();
        EcoString::from(format!(
            "unknown baudelaire module `{name}`, {}",
            Keys::of(&names).plainly(name, "modules")
        ))
    }

    /// The message for an import at a version the registry does not serve.
    fn wrong_version(name: &str) -> EcoString {
        EcoString::from(format!(
            "`@baudelaire/{name}` is served only at {VERSION}: write \
             `@baudelaire/{name}:{VERSION}`. That version tracks what these \
             modules export, not baudelaire's own version, so it does not move \
             when baudelaire is upgraded."
        ))
    }

    /// The manifest served for a module; typst validates its name and version
    /// against the specifier, so both must echo what was asked for.
    fn manifest(name: &str) -> String {
        format!(
            "[package]\nname = \"{name}\"\nversion = \"{VERSION}\"\nentrypoint = \"{ENTRYPOINT}\"\n"
        )
    }

    /// A content fingerprint over the in-memory modules, which have no path a
    /// page could depend on.
    ///
    /// File-backed modules are excluded, and must be: each is already a real
    /// dependency of the pages that import it, and folding the page set in here
    /// would invalidate every page on every structural edit.
    fn fingerprint(&self) -> Hash {
        let memory: BTreeMap<&&str, &Bytes> = self
            .entrypoints
            .iter()
            .filter_map(|(name, entrypoint)| match entrypoint {
                Entrypoint::Memory(source) => Some((name, source)),
                Entrypoint::File(_) => None,
            })
            .collect();
        Hash::of(&memory)
    }
}

/// The project path a mount answers under: it claims a file id only when the id
/// is a *project* path and the prefix covers whole segments, so a project's
/// `.baudelaire/themes` is not read as a file of `.baudelaire/theme`.
struct Prefix<'a>(&'a str);

impl Prefix<'_> {
    /// What `id` names under this prefix, or `None` when it names nothing under
    /// it; the mount point itself is `""`.
    fn strips<'a>(&self, id: &'a FileId) -> Option<&'a str> {
        if id.root() != &VirtualRoot::Project {
            return None;
        }
        let rest = id.vpath().get_without_slash().strip_prefix(self.0)?;
        if rest.is_empty() {
            Some(rest)
        } else {
            rest.strip_prefix('/')
        }
    }
}

/// A package theme's root, served under a project path, a specifier being
/// unable to name a file inside a package.
struct Mount {
    /// The virtual path the theme answers under, as a file id spells it.
    prefix: String,
    root: FsRoot,
}

impl Mount {
    /// The theme's own virtual path for `id`, or `None` if `id` is not under
    /// the mount.
    fn within(&self, id: FileId) -> Option<VirtualPath> {
        VirtualPath::new(Prefix(&self.prefix).strips(&id)?).ok()
    }
}

/// The files `paths { sources }` declared, served under a project path, since
/// a declared file may sit outside the root typst can open.
///
/// Keyed by the whole path under the prefix rather than by a segment, so a name
/// with a `/` in it is served rather than silently missing.
pub(crate) struct Sources {
    files: BTreeMap<String, PathBuf>,
}

/// The mount point as typst spells a path: project-rooted, no leading slash,
/// so it can be matched against a file id and written into a binding.
static PREFIX: std::sync::LazyLock<String> =
    std::sync::LazyLock::new(|| format!("{}/{}", crate::config::Config::SCRATCH, Sources::MOUNT));

impl Sources {
    /// The directory declared sources are mounted under, beside the theme's
    /// own (`Theme::MOUNT`).
    const MOUNT: &'static str = "sources";

    /// The mount point; see [`PREFIX`].
    pub(crate) fn prefix() -> &'static str {
        &PREFIX
    }

    /// What a declared source is served as under the prefix: its declared name
    /// carrying the real file's extension, so a reader sees the kind of file.
    fn key(name: &str, path: &Path) -> String {
        path.extension()
            .and_then(|ext| ext.to_str())
            .map_or_else(|| name.to_owned(), |ext| format!("{name}.{ext}"))
    }

    /// The virtual path a declared source is served at, which is both the
    /// binding a page imports and the id the store answers.
    pub(crate) fn vpath(name: &str, path: &Path) -> String {
        format!("/{}/{}", Self::prefix(), Self::key(name, path))
    }

    /// Build the mount from what the config declared, against `root`.
    fn new(sources: &[(String, PathBuf)], root: &Path) -> Self {
        Self {
            files: sources
                .iter()
                .map(|(name, path)| (Self::key(name, path), root.join(path)))
                .collect(),
        }
    }

    /// The real file a mounted virtual path names, or `None` when the path is
    /// not one, for a reader that resolves a path itself rather than through
    /// the compiler.
    pub(crate) fn real(vpath: &str, sources: &[(String, PathBuf)], root: &Path) -> Option<PathBuf> {
        let key = vpath
            .strip_prefix('/')?
            .strip_prefix(Self::prefix())?
            .strip_prefix('/')?;
        sources
            .iter()
            .find(|(name, path)| Self::key(name, path) == key)
            .map(|(_, path)| root.join(path))
    }

    /// The real file `id` names, or `None` when it names nothing under the
    /// mount.
    fn file(&self, id: FileId) -> Option<&Path> {
        self.files
            .get(Prefix(Self::prefix()).strips(&id)?)
            .map(PathBuf::as_path)
    }
}

/// The project's file loader: generated `@baudelaire/*` modules first, a
/// mounted package theme next, the declared sources after that, and everything
/// else from the filesystem through typst-kit's own loader.
pub(super) struct Files {
    modules: Modules,
    theme: Option<Mount>,
    sources: Sources,
    system: SystemFiles,
}

impl Files {
    pub(super) fn new(
        cx: &ModuleCx,
        root: &Path,
        project: FsRoot,
        packages: SystemPackages,
        theme: Option<(String, PathBuf)>,
        sources: &[(String, PathBuf)],
    ) -> Self {
        Self {
            modules: Modules::new(cx, root),
            theme: theme.map(|(prefix, root)| Mount {
                prefix,
                root: FsRoot::new(root),
            }),
            sources: Sources::new(sources, root),
            system: SystemFiles::new(project, packages),
        }
    }

    /// The mounted theme's own path for `id`, when one is mounted and `id` is
    /// under it.
    fn mounted(&self, id: FileId) -> Option<(&FsRoot, VirtualPath)> {
        let mount = self.theme.as_ref()?;
        Some((&mount.root, mount.within(id)?))
    }

    /// The filesystem path of `id`.
    ///
    /// A generated module has none, and must short-circuit: the system loader
    /// would try to *download* `@baudelaire/html` from the package registry.
    pub(super) fn resolve(&self, id: FileId) -> FileResult<PathBuf> {
        if let Some(path) = self.modules.file(id) {
            return Ok(path.to_path_buf());
        }
        if Modules::owner(&id).is_some() {
            return Err(FileError::Other(Some(EcoString::from(
                "a generated module has no file system path",
            ))));
        }
        if let Some((root, vpath)) = self.mounted(id) {
            return root.resolve(&vpath);
        }
        if let Some(path) = self.sources.file(id) {
            return Ok(path.to_path_buf());
        }
        self.system.resolve(id)
    }

    /// A content fingerprint over the generated modules, for the build cache.
    pub(super) fn fingerprint(&self) -> Hash {
        self.modules.fingerprint()
    }

    /// The build has written its file-backed tables; `true` if one was served
    /// before that, and the store is holding an answer that is now wrong.
    pub(super) fn published(&self) -> bool {
        self.modules.published()
    }
}

impl FileLoader for Files {
    fn load(&self, id: FileId) -> FileResult<Bytes> {
        if let Some(spec) = Modules::owner(&id) {
            return self.modules.load(spec, id.vpath());
        }
        if let Some((root, vpath)) = self.mounted(id) {
            return root.load(&vpath);
        }
        if let Some(path) = self.sources.file(id) {
            return std::fs::read(path)
                .map(Bytes::new)
                .map_err(|why| FileError::from_io(why, path));
        }
        self.system.load(id)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use typst::syntax::{RootedPath, package::PackageSpec};

    #[test]
    fn a_source_is_served_at_the_path_it_is_bound_to() {
        let declared = vec![
            ("changelog".to_owned(), PathBuf::from("../CHANGELOG.md")),
            ("notes".to_owned(), PathBuf::from("notes")),
        ];
        let sources = Sources::new(&declared, Path::new("/project"));
        let id = |path: &str| {
            FileId::new(RootedPath::new(
                VirtualRoot::Project,
                VirtualPath::new(path).expect("a valid vpath"),
            ))
        };

        let vpath = Sources::vpath("changelog", Path::new("../CHANGELOG.md"));
        assert_eq!(vpath, "/.baudelaire/sources/changelog.md");
        assert_eq!(
            sources.file(id(&vpath)),
            Some(Path::new("/project/../CHANGELOG.md")),
            "the binding names what the store serves"
        );
        assert_eq!(
            sources.file(id("/.baudelaire/sources/notes")),
            Some(Path::new("/project/notes"))
        );
        assert_eq!(sources.file(id("/.baudelaire/sources/other.md")), None);
        assert_eq!(sources.file(id("/.baudelaire/sourced/changelog.md")), None);
        assert_eq!(sources.file(id("/CHANGELOG.md")), None);
    }

    #[test]
    fn a_mount_claims_only_what_is_under_it() {
        let mount = Mount {
            prefix: ".baudelaire/theme".to_owned(),
            root: FsRoot::new(PathBuf::from("/packages/plume")),
        };
        let id = |path: &str| {
            FileId::new(RootedPath::new(
                VirtualRoot::Project,
                VirtualPath::new(path).expect("a valid vpath"),
            ))
        };
        assert_eq!(
            mount
                .within(id("/.baudelaire/theme/templates/page.typ"))
                .map(VirtualPath::into_with_slash)
                .as_deref(),
            Some("/templates/page.typ")
        );
        assert!(mount.within(id("/.baudelaire/themes/page.typ")).is_none());
        assert!(mount.within(id("/templates/page.typ")).is_none());
        assert!(
            mount
                .within(FileId::new(RootedPath::new(
                    VirtualRoot::Package(PackageSpec {
                        namespace: "preview".into(),
                        name: "plume".into(),
                        version: VERSION,
                    }),
                    VirtualPath::new(".baudelaire/theme/lib.typ").expect("a valid vpath"),
                )))
                .is_none()
        );
    }

    #[test]
    fn the_registry_serves_memory_regardless_of_what_is_installed() {
        let modules = Modules::new(
            &ModuleCx {
                context: &Value::None,
                #[cfg(feature = "markdown")]
                markdown: &crate::config::MarkdownConfig::default(),
                sources: &[],
            },
            Path::new("."),
        );
        let spec = PackageSpec {
            namespace: NAMESPACE.into(),
            name: "html".into(),
            version: VERSION,
        };
        let served = modules
            .load(&spec, &VirtualPath::new(ENTRYPOINT).expect("a valid vpath"))
            .expect("html is served");
        assert!(String::from_utf8_lossy(&served).contains(Html.body()));
    }
}
