//! The changelog is a page of the docs site, and this is what keeps it honest.
//!
//! `CHANGELOG.md` stays the only copy anyone edits. The page is that file with
//! the frontmatter a page needs in front of it, generated by `just
//! changelog-page` and committed, for the reason `tests/reference.rs` gives for
//! the config reference: the docs site is a real baudelaire site, so its pages
//! have to exist on disk before it builds.
//!
//! A stale copy fails here rather than publishing a changelog that has stopped
//! matching the one the release workflow reads.

/// Relative to the crate root, which is where cargo runs an integration test.
const PATH: &str = "docs/content/lookup/changelog.md";
const SOURCE: &str = "CHANGELOG.md";

/// The frontmatter the docs site needs, in the KDL a markdown page declares.
/// `order` puts it last in the `lookup` group, after the four reference pages.
const FRONTMATTER: &str = "---\n\
    title \"Changelog\"\n\
    order 5\n\
    template \"changelog.typ\"\n\
    description \"Every released version of baudelaire, and what changed in it.\"\n\
    ---\n";

/// The page as it should read: the frontmatter, then the changelog without its
/// top heading, which the page template already draws from the title.
fn expected() -> String {
    let source = std::fs::read_to_string(SOURCE).expect("read the changelog");
    let body = source
        .strip_prefix("# Changelog\n")
        .unwrap_or(&source)
        .trim_start_matches('\n');
    format!("{FRONTMATTER}\n{body}")
}

/// Regenerate with `just changelog-page`, which is this test with `BLESS=1`.
#[test]
fn the_checked_in_changelog_page_matches_the_changelog() {
    let expected = expected();

    if std::env::var_os("BLESS").is_some() {
        std::fs::write(PATH, &expected).expect("write the changelog page");
        return;
    }

    let actual = std::fs::read_to_string(PATH).unwrap_or_default();
    assert_eq!(
        actual, expected,
        "{PATH} is out of date with {SOURCE}; run `just changelog-page`"
    );
}

/// The page has to declare frontmatter a build accepts, or the docs site fails
/// on a file this test just told everyone was correct. Cheap to state, and it
/// is the half the diff above cannot see.
#[test]
fn the_generated_page_opens_with_a_frontmatter_block() {
    let page = expected();
    let mut lines = page.lines();
    assert_eq!(lines.next(), Some("---"), "the block has to open the file");
    assert!(
        lines.any(|line| line == "---"),
        "the block has to close again"
    );
    assert!(
        page.contains("title \"Changelog\""),
        "the page needs a title, which its template reads"
    );
}
