//! The generated config reference is checked in, and this is what keeps it
//! honest.
//!
//! The docs site is a real baudelaire site, so its pages have to exist on disk
//! before it builds; the reference cannot be generated during the docs build
//! without making that build depend on this crate's internals. So it is
//! generated by `just reference` and committed, and a stale copy fails here
//! rather than shipping a reference that describes a config the parser no
//! longer accepts.

use baudelaire::config::reference::{Page, Reference};

/// Relative to the crate root, which is where cargo runs an integration test.
const PATH: &str = "docs/content/guide/reference.typ";

/// Regenerate with `just reference`, which is this test with `BLESS=1`.
#[test]
fn the_checked_in_reference_matches_the_dispatch_tables() {
    let expected = Page(&Reference::new()).to_string();

    if std::env::var_os("BLESS").is_some() {
        std::fs::write(PATH, &expected).expect("write the reference");
        return;
    }

    let actual = std::fs::read_to_string(PATH).unwrap_or_default();
    assert_eq!(
        actual, expected,
        "{PATH} is out of date with the config dispatch tables; run `just reference`"
    );
}

/// The walk reaches the leaves, not just the top level: a nested block's keys
/// carry their full dotted path, which is what `baudelaire reference <key>`
/// looks them up by.
#[test]
fn the_walk_descends_into_nested_blocks() {
    let reference = Reference::new();
    let paths = reference.paths();

    for expected in [
        "paths.content",
        "assets.images.responsive.widths",
        "assets.images.optimize.png.level",
        "generate.feed.limit",
        "deploy.ssh.key",
        "content.collections.paginate.size",
    ] {
        assert!(paths.contains(&expected), "missing {expected}");
    }
}

/// `profiles` is the one key that must not recurse: a profile accepts every
/// top-level key, including `profiles` itself, so walking into it would not
/// terminate. It is listed, and it has no children.
#[test]
fn profiles_is_listed_without_recursing() {
    let reference = Reference::new();
    let paths = reference.paths();

    assert!(paths.contains(&"profiles"));
    assert!(
        !paths.iter().any(|p| p.starts_with("profiles.")),
        "profiles recursed: {:?}",
        paths
            .iter()
            .filter(|p| p.starts_with("profiles."))
            .collect::<Vec<_>>()
    );
}

/// Narrowing returns the named key and its subtree, re-based so the named key
/// sits at depth zero, and nothing else.
#[test]
fn narrowing_returns_only_that_subtree() {
    let narrowed = Reference::at("deploy.s3").expect("deploy.s3 exists");
    let entries = narrowed.entries();

    assert_eq!(entries[0].path, "deploy.s3");
    assert_eq!(entries[0].depth, 0, "the named key is re-based to the root");
    assert!(
        entries[1..]
            .iter()
            .all(|e| e.path.starts_with("deploy.s3.")),
        "a sibling leaked in"
    );
    assert!(entries.iter().any(|e| e.key == "bucket"));
    // `deploy.ssh` is a sibling, and must not be here.
    assert!(!entries.iter().any(|e| e.key == "host"));
}

/// An unknown path is `None`, not an empty reference: "no such key" and "this
/// key has no settings" are different answers, and the CLI turns only the first
/// into an error.
#[test]
fn an_unknown_path_is_absent_rather_than_empty() {
    assert!(Reference::at("assets.imgs").is_none());
    assert!(Reference::at("").is_none());
}

/// Every key says something. A row with no description would render as a blank
/// column in the docs and tell a reader nothing.
#[test]
fn every_key_carries_a_description() {
    for entry in Reference::new().entries() {
        assert!(
            !entry.doc.trim().is_empty(),
            "{} has no description",
            entry.path
        );
        assert!(
            entry.doc.ends_with('.'),
            "{} should read as a sentence: {:?}",
            entry.path,
            entry.doc
        );
    }
}
