// Generated by `just reference` from the dispatch tables in
// `src/config/parse.rs`. Do not edit: `cargo test --test reference`
// fails when this file and those tables disagree.

#let frontmatter = (
  title: "Config reference",
  description: "Every key `config.kdl` accepts, with its value shape.",
  order: 5,
)

Every key the config accepts, in the order the parser declares them. Generated from the parser itself, so it cannot drift from what actually parses.

/ #raw("site") #raw("text"): The site's name, used in titles, feeds and metadata.
/ #raw("url") #raw("url"): The absolute base URL. Sitemaps, feeds and social cards cannot be generated without it.
/ #raw("lang") #raw("text"): The default language code, e.g. `en`.
/ #raw("author") #raw("text"): The default author, used by any page naming none.
/ #raw("theme") #raw("text"): A theme directory whose templates and assets this site layers over.

== `paths`

Where the content, output and asset trees live.

/ #raw("content") #raw("path"): The content tree of `.typ` pages.
/ #raw("dist") #raw("path"): Where the built site is written.
/ #raw("assets") #raw("path"): Assets that go through the pipeline: CSS, JS, images.
/ #raw("static") #raw("path"): Files copied to the output verbatim, untouched by the pipeline.
/ #raw("templates") #raw("path"): Where layouts and partials are imported from.

== `content`

What the content tree holds and how it is read.

/ #raw("index") #raw("text"): The filename stem that publishes at its directory's own URL, without extension.
/ #raw("future") #raw("flag"): Build pages dated later than now.

=== `content.draft`

Whether drafts are built, and where they land.

/ #raw("build") #raw("flag"): Build draft pages at all.
/ #raw("suffix") #raw("text"): Appended to a draft's URL, so a built draft cannot collide with the published page.

=== `content.collections`

One block per collection, each named by its id.

/ #raw("glob") #raw("text"): Which content files belong to this collection.
/ #raw("sort") #raw("order | date | title"): What the collection's members are ordered by.
/ #raw("reverse") #raw("flag"): Reverse that order.
/ #raw("permalink") #raw("template"): The URL pattern its pages publish at, e.g. `/{slug}/`.
/ #raw("template") #raw("text"): The layout its pages render through.

==== `content.collections.paginate`

Generate an index over the collection. Its presence turns the index on.

/ #raw("size") #raw("number"): Pages per index page. Omitted, the index is one page.
/ #raw("template") #raw("text"): The layout the index renders through.
/ #raw("mount") #raw("text"): Where the index publishes, if not at the collection's own path.
/ #raw("prefix") #raw("text"): The path segment before a page number, as in `/posts/page/2/`.

=== `content.taxonomies`

One line per taxonomy, each named by its id.

/ #raw("key") #raw("text"): The frontmatter field its terms are read from. Defaults to the taxonomy's own id.
/ #raw("listing") #raw("flag"): Generate a page per term, and an index of the terms.
/ #raw("template") #raw("text"): The layout those listings render through.
/ #raw("paginate") #raw("number"): Pages per term listing.
/ #raw("prefix") #raw("text"): The path segment its listings publish under.

== `languages`

One block per language, each named by its code.

/ #raw("name") #raw("text"): The language's name in its own language, for a switcher.
/ #raw("dir") #raw("text"): Writing direction, `ltr` or `rtl`.
/ #raw("site") #raw("text"): The site name in this language.
/ #raw("author") #raw("text"): The default author in this language.
/ #raw("strings") #raw("key=value .."): This language's UI string table, as free `key=value` pairs.

== `assets`

The pipeline applied to the asset tree.

/ #raw("minify") #raw("flag"): Minify CSS and JavaScript.
/ #raw("bundle") #raw("flag"): Bundle JavaScript modules into one file per entry point.
/ #raw("fingerprint") #raw("flag"): Put a content hash in each asset's filename, so it can be cached forever.

=== `assets.images`

Image markup and build-time processing.

/ #raw("lazy") #raw("flag"): Mark images `loading="lazy"`.
/ #raw("extract") #raw("flag"): Write images typst embedded in the page out as their own files.

==== `assets.images.optimize`

Per-format lossless recompression.


===== `assets.images.optimize.png`

Optimize PNGs. Its presence turns them on; the attributes tune it.

/ #raw("level") #raw("number"): Compression effort, 0 to 6. Higher is slower and smaller.
/ #raw("strip") #raw("none | safe | all"): Which ancillary chunks to discard.

===== `assets.images.optimize.jpeg`

Optimize JPEGs. Its presence turns them on; the attributes tune it.

/ #raw("quality") #raw("number"): Encoder quality, 1 to 100.

==== `assets.images.responsive`

Generate width variants and a `srcset`. Its presence turns them on.

/ #raw("widths") #raw("number .."): The pixel widths to emit a variant at.
/ #raw("quality") #raw("number"): Encoder quality for the generated variants, 1 to 100.
/ #raw("sizes") #raw("text"): The `sizes` attribute put on every responsive image.

== `html`

Post-processing of typst's HTML output.

/ #raw("pretty") #raw("flag"): Indent the emitted HTML.
/ #raw("embed") #raw("flag"): Inline processed assets into the page as `data:` URIs.
/ #raw("meta") #raw("flag"): Emit the `\<meta\>` description, Open Graph and Twitter tags.
/ #raw("anchors") #raw("flag"): Give every heading an `id` and a self link.
/ #raw("jsonld") #raw("flag"): Emit JSON-LD structured data for each page.
/ #raw("spans") #raw("flag"): Stamp each element with the source span it came from, so `serve` can open it.
/ #raw("footnotes") #raw("text .."): The elements a page's footnotes belong inside, most specific first.
/ #raw("highlight") #raw("key=value .."): Rewrite syntax-highlight colours to classes. Bare, it uses hex classes; a block names the scopes.

== `links`

The shape of generated URLs, and how strictly links are checked.

/ #raw("style") #raw("clean | flat"): Whether URLs are directories (`clean`) or `.html` files (`flat`).
/ #raw("strict") #raw("flag"): Fail the build on a broken internal link instead of warning.
/ #raw("external") #raw("flag"): Also check outbound `http(s)` links over the network.

== `generate`

The files a build emits beside the pages.

/ #raw("sitemap") #raw("flag"): Write `sitemap.xml`.
/ #raw("redirects") #raw("flag"): Write a `\_redirects` file from each page's declared aliases.
/ #raw("headers") #raw("flag"): Write a `\_headers` file from the caching policy.

=== `generate.robots`

Write `robots.txt`. Its presence turns it on.

/ #raw("disallow") #raw("text .."): Paths to disallow, one word each.

=== `generate.llms`

Write `llms.txt`. Its presence turns it on.

/ #raw("summary") #raw("text"): A one-line description of the site, put at the top of the file.

=== `generate.feed`

Write syndication feeds.

/ #raw("formats") #raw("rss | atom | json"): Which feed formats to write, one word each.
/ #raw("limit") #raw("number"): How many of the newest pages a feed carries.
/ #raw("terms") #raw("flag"): Also write a feed per taxonomy term.

=== `generate.search`

Write a client-side search index.

/ #raw("formats") #raw("json | inverted"): Which index formats to write, one word each.
/ #raw("fields") #raw("title | body | tags"): Which parts of a page go into the index, one word each.
/ #raw("stopwords") #raw("text .."): Words to leave out of the index, one word each.
/ #raw("minimum") #raw("number"): The shortest word the index keeps.
/ #raw("ui") #raw("flag"): Ship the bundled search box as well as the index.

=== `generate.cards`

Draw a social card per page. Its presence turns it on.

/ #raw("template") #raw("text"): The typst template each card is drawn with.
/ #raw("width") #raw("number"): Card width in pixels.
/ #raw("height") #raw("number"): Card height in pixels.

=== `generate.pdf`

Typeset PDFs beside the pages.


==== `generate.pdf.pages`

A PDF per page, beside its HTML. Its presence turns it on.

/ #raw("template") #raw("text"): The typst template each page is typeset with.

==== `generate.pdf.bundle`

Many pages as one document. Needs a target named below.

/ #raw("template") #raw("text"): The typst template the bundle is typeset with.
/ #raw("collections") #raw("text .."): Which collections the bundle gathers, one word each.
/ #raw("site") #raw("flag"): Bundle the whole site rather than named collections.

== `navigation`

How a visitor moves between the built pages.


=== `navigation.spa`

Client-side navigation between pages. Its presence turns it on.

/ #raw("root") #raw("text"): The element swapped out on navigation.
/ #raw("prefetch") #raw("none | hover | visible"): When to fetch a page ahead of the click.

=== `navigation.standalone`

Export the whole site as one HTML file. Its presence turns it on.

/ #raw("file") #raw("path"): The single file the site is written to.
/ #raw("entry") #raw("text"): The page that file opens on.
/ #raw("router") #raw("hash | history"): How it addresses pages once opened.

=== `navigation.speculation`

Browser prefetch and prerender hints. Its presence turns them on.

/ #raw("prefetch") #raw("none | conservative | moderate | eager | immediate"): How eagerly the browser fetches a linked page.
/ #raw("prerender") #raw("none | conservative | moderate | eager | immediate"): How eagerly it renders one ahead of the click.
/ #raw("prune") #raw("flag"): Delete anything under the output directory that this build did not produce.

== `cache`

Where incremental build state lives, and whether to use it.

/ #raw("dir") #raw("path"): Where incremental build state is kept.
/ #raw("incremental") #raw("flag"): Reuse that state. Off, every build is a cold one.

== `caching`

The `Cache-Control` policy uploaded files are given.

/ #raw("immutable") #raw("text"): The `Cache-Control` value for fingerprinted assets, which can be cached forever.
/ #raw("default") #raw("text"): The `Cache-Control` value for everything else.

== `typst`

Typst engine knobs: language features, inputs, package registry.

/ #raw("features") #raw("text .."): Typst language features to enable, or `-name` to disable one. `html` cannot be removed.
/ #raw("inputs") #raw("key=value .."): Values passed to every compile as `sys.inputs`, as free `key=value` pairs.
/ #raw("registry") #raw("url"): Where typst packages are fetched from.
/ #raw("client") #raw("key=value .."): Constants exposed to client-side JavaScript, as free `key=value` pairs.

== `hooks`

External commands run before and after the build.

/ #raw("before") #raw("text .."): Commands run before the asset pipeline, so what they generate is picked up.
/ #raw("after") #raw("text .."): Commands run once the output directory is written.

== `announce`

Where to announce the site's metadata.


=== `announce.standard`

Announce to standard.site over atproto. Its presence turns it on.

/ #raw("handle") #raw("text"): The atproto handle the site is announced under.
/ #raw("did") #raw("text"): That handle's DID, if it should not be resolved at build time.
/ #raw("pds") #raw("url"): The personal data server the record is written to.
/ #raw("discover") #raw("flag"): Resolve the PDS from the handle rather than trusting `pds`.
/ #raw("icon") #raw("path"): An icon published with the record.

==== `announce.standard.verify`

Which handle-verification artifacts the build emits.

/ #raw("wellknown") #raw("flag"): Write `/.well-known/atproto-did`.
/ #raw("links") #raw("flag"): Add the verification links to the page head.

== `deploy`

Where `baudelaire deploy` uploads the built site.


=== `deploy.s3`

Upload to S3 or an S3-compatible bucket. Its presence turns it on.

/ #raw("bucket") #raw("text"): The bucket uploaded into.
/ #raw("endpoint") #raw("url"): The API endpoint, for an S3-compatible host such as R2.
/ #raw("region") #raw("text"): The bucket's region.
/ #raw("prefix") #raw("text"): A key prefix every uploaded object goes under.
/ #raw("delete") #raw("flag"): Delete remote objects this build did not produce.

=== `deploy.ssh`

Upload over SSH. Its presence turns it on.

/ #raw("host") #raw("text"): The host uploaded to.
/ #raw("path") #raw("text"): The remote directory the site is written into.
/ #raw("port") #raw("number"): The SSH port.
/ #raw("user") #raw("text"): The user to connect as.
/ #raw("key") #raw("path"): The private key to authenticate with. Prefer an ed25519 key.
/ #raw("strict") #raw("flag"): Refuse to connect to a host whose key is not already known.
/ #raw("delete") #raw("flag"): Delete remote files this build did not produce.

== `serve`

The development server.

/ #raw("port") #raw("number"): The port the dev server listens on.
/ #raw("bind") #raw("text"): The address it binds. Defaults to loopback; it has no authentication.
/ #raw("open") #raw("flag"): Open a browser when the server starts.
/ #raw("watch") #raw("flag"): Watch the sources and rebuild. Off, it serves what is already built.
/ #raw("include") #raw("text .."): Extra paths to watch, one word each.
/ #raw("exclude") #raw("text .."): Paths to leave unwatched, one word each.
/ #raw("editor") #raw("text .."): The command alt-clicking a preview element runs, program and arguments as separate words.

== `profiles`

Named overlays, each selected with `--profile` and each accepting any key on this page.

