//! The mapping from a source image's request path to its responsive width
//! variants.
//!
//! Built by the engine's asset pipeline (which generates the downscaled copies)
//! and shared read-only into the render layer, where the [`super::sources`]
//! transform turns each `<img>` that names a mapped source into one carrying a
//! `srcset`. The recorded URLs are the *authored* (pre-fingerprint) paths, so
//! the later [`super::fingerprint`] transform rewrites them alongside every
//! other reference.

use std::collections::BTreeMap;

use crate::graph::Hash;

/// One responsive candidate: a variant's authored URL and its intrinsic width,
/// the `srcset` width descriptor (`photo-480.jpg 480w`).
#[derive(Debug, Clone, Hash)]
pub struct Candidate {
    pub url: String,
    pub width: u32,
}

/// The variant-manifest entries a page's images consulted: for each source path
/// probed, a digest of the candidates it found, or `None` when the path named no
/// responsive image.
///
/// A page's dependency on the responsive pipeline, which the per-page tracker
/// cannot see: the variants are generated by the asset pipeline and matched
/// render-side, so typst never reads them. Recorded per page and revalidated on
/// a cache hit, so regenerating one image's variants rebuilds the pages showing
/// it rather than the site.
///
/// The `None` entries matter as much as the rest: an image with no variants
/// today gets some when `responsive` widths change or the source grows past a
/// threshold, and the page showing it has to pick up the new `srcset`.
pub type SrcSetDeps = BTreeMap<String, Option<Hash>>;

/// What a source path matched in the manifest, and the entry that decided it.
///
/// The two travel together so a caller cannot read the candidates without also
/// being handed the dependency it just incurred.
pub struct Variants<'a> {
    /// The candidates, ascending by width, or `None` for a path that names no
    /// responsive image.
    pub candidates: Option<&'a [Candidate]>,
    /// The manifest entry consulted, with its digest at the time.
    pub probed: SrcSetDeps,
}

/// Maps a source image's authored request path (`/assets/photo.jpg`) to its
/// width candidates, the original included as the largest. Ordered so its hash
/// is deterministic and folds into the build cache.
#[derive(Debug, Default, Clone, Hash)]
pub struct SrcSets {
    map: BTreeMap<String, Vec<Candidate>>,
}

impl SrcSets {
    /// Record that `source` (an authored request path) is served at `width` by
    /// the variant at `url` (also an authored path).
    pub fn record(&mut self, source: String, width: u32, url: String) {
        self.map
            .entry(source)
            .or_default()
            .push(Candidate { url, width });
    }

    /// The `srcset` candidates for a source path, together with the dependency
    /// that reading them creates.
    pub fn candidates(&self, source: &str) -> Variants<'_> {
        let candidates = self.map.get(source);
        Variants {
            candidates: candidates.map(Vec::as_slice),
            probed: BTreeMap::from([(source.to_owned(), candidates.map(Hash::of))]),
        }
    }

    /// Every source path's candidate digest, for the build cache to revalidate a
    /// page's recorded [`SrcSetDeps`] against. Digested here rather than in the
    /// cache so the recorded and the current digest can never be computed two
    /// different ways.
    pub fn digests(&self) -> BTreeMap<String, Hash> {
        self.map
            .iter()
            .map(|(source, candidates)| (source.clone(), Hash::of(candidates)))
            .collect()
    }
}
