//! The tables the build hands templates as generated Typst source files: the
//! site's section tree and its page catalogue.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::PathBuf;

use crate::codegen::{Let, Value};
use crate::config::Config;
use crate::generated::{File, Generated};

/// One per-language table, written out as Typst source and imported as
/// `@baudelaire/<module>`.
///
/// A file rather than a field of each page's generated wrapper, whose text is
/// that page's cache fingerprint and so must name nothing site-wide.
pub(crate) struct Table {
    /// The module this backs, and the accessor it exports: `sections(lang)`.
    module: &'static str,
    /// The table, keyed by language code.
    trees: BTreeMap<String, Value>,
}

impl Table {
    /// The private binding holding the per-language values.
    const TABLE: &'static str = "__table";

    pub(crate) fn new(module: &'static str, trees: BTreeMap<String, Value>) -> Self {
        Self { module, trees }
    }

    /// Where this file lives, relative to the project root, under
    /// [`Config::SCRATCH`], which `clean` wipes and `serve` does not watch.
    pub(crate) fn path(&self) -> PathBuf {
        Self::of(self.module)
    }

    /// The same path for a module named directly, before any [`Table`] exists.
    pub(crate) fn of(module: &str) -> PathBuf {
        Config::scratch(crate::config::Scratch::Generated).join(format!("{module}.typ"))
    }

    /// The table with nothing in it: what a module reads as before a build has
    /// written the real one.
    pub(crate) fn empty(module: &'static str) -> Self {
        Self::new(module, BTreeMap::new())
    }

    /// The generated Typst source: a function rather than a bare dict, so an
    /// unbuilt language yields an empty value instead of failing the page.
    pub(crate) fn source(&self) -> String {
        let table = Value::dict(
            self.trees
                .iter()
                .map(|(lang, tree)| (lang.clone(), tree.clone())),
        );
        let mut out =
            String::from("// Generated by baudelaire. Rewritten on every build; edits are lost.\n");
        let _ = writeln!(out, "{}", Let(Self::TABLE, &table));
        let _ = writeln!(
            out,
            "#let {}(lang) = {}.at(lang, default: ())",
            self.module,
            Self::TABLE
        );
        out
    }
}

/// Written before any page compiles, so a template's `#import` resolves on the
/// first build in a fresh checkout.
impl Generated for Table {
    fn files(&self) -> Vec<File> {
        vec![File::new(self.path(), self.source())]
    }
}

#[cfg(test)]
mod tests {
    use super::Table;
    use crate::codegen::Value;
    use crate::world::module::{PAGES, SECTIONS};
    use std::collections::BTreeMap;

    fn sections(langs: &[(&str, &str)]) -> Table {
        Table::new(
            SECTIONS,
            langs
                .iter()
                .map(|(lang, title)| {
                    (
                        (*lang).to_owned(),
                        Value::array([Value::dict([("title", Value::str(title))])]),
                    )
                })
                .collect::<BTreeMap<_, _>>(),
        )
    }

    #[test]
    fn binds_every_language_behind_one_accessor() {
        let source = sections(&[("en", "Home"), ("pt-BR", "Início")]).source();

        assert!(source.contains("en: "), "{source}");
        assert!(source.contains("pt-BR: "), "{source}");
        assert!(source.contains("Início"), "{source}");
        assert!(
            source.contains("#let sections(lang) = __table.at(lang, default: ())"),
            "{source}"
        );
    }

    #[test]
    fn the_accessor_is_named_after_the_module() {
        let source = Table::new(PAGES, BTreeMap::new()).source();

        assert!(
            source.contains("#let pages(lang) = __table.at(lang, default: ())"),
            "{source}"
        );
    }

    #[test]
    fn a_site_with_no_pages_still_generates_an_importable_file() {
        let source = sections(&[]).source();

        assert!(source.contains("#let __table = (:)"), "{source}");
    }

    #[test]
    fn the_path_is_scratch_state_so_clean_and_the_watcher_agree() {
        let path = sections(&[]).path();

        assert!(
            path.starts_with(crate::config::Config::SCRATCH),
            "{}",
            path.display()
        );
    }
}
