//! The tables the build hands templates as generated Typst source files: the
//! site's section tree and its page catalogue.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::codegen::{Let, Value};
use crate::error::Result;
use crate::world::module::generated;

/// One per-language table, written out as Typst source and imported as
/// `@baudelaire/<module>`.
///
/// Deliberately a *file* rather than a field of each page's generated wrapper.
/// The wrapper's text is the page's cache fingerprint, so a table derived from
/// the whole site embedded there folds every title and URL into every page's
/// identity: one retitle, one rename, one new post, and the whole site
/// recompiles. Written out instead, the import is an ordinary file read, so
/// typst's own dependency tracking records it and the table invalidates exactly
/// the pages whose template reads it.
///
/// The files are generated build state, not source: rewritten every build,
/// never edited, and safe to delete.
pub(in crate::engine) struct Generated {
    /// The module this backs, which is also the accessor a template calls:
    /// `@baudelaire/sections` exports `sections(lang)`.
    module: &'static str,
    /// The table, keyed by language code.
    trees: BTreeMap<String, Value>,
}

impl Generated {
    /// The private binding holding the per-language values, which callers reach
    /// only through the accessor named after the module.
    const TABLE: &'static str = "__table";

    pub(in crate::engine) fn new(module: &'static str, trees: BTreeMap<String, Value>) -> Self {
        Self { module, trees }
    }

    /// Where this file lives, relative to the project root.
    ///
    /// Templates never spell it: they import `@baudelaire/<module>`, and the
    /// module registry resolves that to this path. The path is the registry's
    /// to decide, so it is asked rather than restated.
    pub(in crate::engine) fn path(&self) -> PathBuf {
        generated(self.module)
    }

    /// Write the file under `root`, creating its directory.
    ///
    /// Run once per build and before any page compiles, because a template's
    /// `#import` has to resolve on the very first build in a fresh checkout,
    /// where nothing has written it yet.
    pub(in crate::engine) fn write(&self, root: &Path) -> Result<()> {
        crate::fs::write_all(root.join(self.path()), self.source())
    }

    /// The generated Typst source.
    ///
    /// A function rather than a bare dict so a template reads `sections(page.lang)`
    /// on a multilingual site and a single-language one alike, and so an unbuilt
    /// language yields an empty value instead of failing the page that asked.
    fn source(&self) -> String {
        let table = Value::dict(
            self.trees
                .iter()
                .map(|(lang, tree)| (lang.clone(), tree.clone())),
        );
        let mut out =
            String::from("// Generated by baudelaire. Rewritten on every build; edits are lost.\n");
        let _ = writeln!(out, "{}", Let(Self::TABLE, &table));
        let _ = writeln!(
            out,
            "#let {}(lang) = {}.at(lang, default: ())",
            self.module,
            Self::TABLE
        );
        out
    }
}

#[cfg(test)]
mod tests {
    use super::Generated;
    use crate::codegen::Value;
    use crate::world::module::{PAGES, SECTIONS};
    use std::collections::BTreeMap;

    fn sections(langs: &[(&str, &str)]) -> Generated {
        Generated::new(
            SECTIONS,
            langs
                .iter()
                .map(|(lang, title)| {
                    (
                        (*lang).to_owned(),
                        Value::array([Value::dict([("title", Value::str(title))])]),
                    )
                })
                .collect::<BTreeMap<_, _>>(),
        )
    }

    #[test]
    fn binds_every_language_behind_one_accessor() {
        // A regional tag has to survive as a key. Typst identifiers are
        // kebab-case, so `pt-BR` needs no quoting, and `codegen` quotes the
        // keys that would not parse; this pins that the tree goes through it
        // rather than formatting keys itself.
        let source = sections(&[("en", "Home"), ("pt-BR", "Início")]).source();

        assert!(source.contains("en: "), "{source}");
        assert!(source.contains("pt-BR: "), "{source}");
        assert!(source.contains("Início"), "{source}");
        assert!(
            source.contains("#let sections(lang) = __table.at(lang, default: ())"),
            "{source}"
        );
    }

    /// Each file names its own accessor, so two of them can be imported into
    /// one template without colliding.
    #[test]
    fn the_accessor_is_named_after_the_module() {
        let source = Generated::new(PAGES, BTreeMap::new()).source();

        assert!(
            source.contains("#let pages(lang) = __table.at(lang, default: ())"),
            "{source}"
        );
    }

    #[test]
    fn a_site_with_no_pages_still_generates_an_importable_file() {
        // The import must resolve before it is useful: a template that reads
        // the tree cannot be made to fail by an empty site.
        let source = sections(&[]).source();

        assert!(source.contains("#let __table = (:)"), "{source}");
    }

    #[test]
    fn the_path_is_scratch_state_so_clean_and_the_watcher_agree() {
        let path = sections(&[]).path();

        assert!(
            path.starts_with(crate::config::Config::SCRATCH),
            "{}",
            path.display()
        );
    }
}
