//! The site's section tree, as a generated Typst source file templates import.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use crate::codegen::{Let, Value};
use crate::error::Result;
use crate::world::module::{SECTIONS, generated};

/// Every built language's section tree, written out as Typst source.
///
/// Deliberately a *file* rather than a field of each page's generated wrapper.
/// The wrapper's text is the page's cache fingerprint, so a tree embedded there
/// folds every title and URL on the site into every page's identity: one
/// retitle, one rename, one new post, and the whole site recompiles. Written
/// out instead, the import is an ordinary file read, so typst's own dependency
/// tracking records it and the tree invalidates exactly the pages whose
/// template reads it.
///
/// The file is generated build state, not source: rewritten every build, never
/// edited, and safe to delete.
pub(in crate::engine) struct Sections(BTreeMap<String, Value>);

impl Sections {
    /// The binding templates import: `sections(lang)`.
    const BINDING: &'static str = "sections";
    /// The private binding holding the per-language trees, which callers reach
    /// only through [`Sections::BINDING`].
    const TREES: &'static str = "__trees";

    /// Where the file lives, relative to the project root.
    ///
    /// Templates never spell this: they import `@baudelaire/sections`, and the
    /// module registry resolves that to this file. The path is the registry's
    /// to decide, so it is asked rather than restated.
    pub(in crate::engine) fn path() -> PathBuf {
        generated(SECTIONS)
    }

    /// The per-language trees, keyed by language code.
    pub(in crate::engine) fn new(trees: BTreeMap<String, Value>) -> Self {
        Self(trees)
    }

    /// Write the file under `root`, creating its directory.
    ///
    /// Run once per build and before any page compiles, because a template's
    /// `#import` has to resolve on the first build in a fresh checkout, where
    /// nothing has written it yet.
    pub(in crate::engine) fn write(&self, root: &Path) -> Result<()> {
        crate::fs::write_all(root.join(Self::path()), self.source())
    }

    /// The generated Typst source.
    ///
    /// A function rather than a bare dict so a template reads
    /// `sections(page.lang)` on a multilingual site and a single-language one
    /// alike, and so an unbuilt language yields an empty tree instead of
    /// failing the page that asked.
    fn source(&self) -> String {
        let trees = Value::dict(
            self.0
                .iter()
                .map(|(lang, tree)| (lang.clone(), tree.clone())),
        );
        let mut out =
            String::from("// Generated by baudelaire. Rewritten on every build; edits are lost.\n");
        let _ = writeln!(out, "{}", Let(Self::TREES, &trees));
        let _ = writeln!(
            out,
            "#let {}(lang) = {}.at(lang, default: ())",
            Self::BINDING,
            Self::TREES
        );
        out
    }
}

#[cfg(test)]
mod tests {
    use super::Sections;
    use crate::codegen::Value;
    use std::collections::BTreeMap;

    fn sections(langs: &[(&str, &str)]) -> Sections {
        Sections::new(
            langs
                .iter()
                .map(|(lang, title)| {
                    (
                        (*lang).to_owned(),
                        Value::array([Value::dict([("title", Value::str(title))])]),
                    )
                })
                .collect::<BTreeMap<_, _>>(),
        )
    }

    #[test]
    fn binds_every_language_behind_one_accessor() {
        // A regional tag has to survive as a key. Typst identifiers are
        // kebab-case, so `pt-BR` needs no quoting, and `codegen` quotes the
        // keys that would not parse; this pins that the tree goes through it
        // rather than formatting keys itself.
        let source = sections(&[("en", "Home"), ("pt-BR", "Início")]).source();

        assert!(source.contains("en: "), "{source}");
        assert!(source.contains("pt-BR: "), "{source}");
        assert!(source.contains("Início"), "{source}");
        assert!(
            source.contains("#let sections(lang) = __trees.at(lang, default: ())"),
            "{source}"
        );
    }

    #[test]
    fn a_site_with_no_pages_still_generates_an_importable_file() {
        // The import must resolve before it is useful: a template that reads
        // the tree cannot be made to fail by an empty site.
        let source = sections(&[]).source();

        assert!(source.contains("#let __trees = (:)"), "{source}");
    }

    #[test]
    fn the_path_is_scratch_state_so_clean_and_the_watcher_agree() {
        let path = Sections::path();

        assert!(
            path.starts_with(crate::config::Config::SCRATCH),
            "{}",
            path.display()
        );
    }
}
